name: predictability-dimension
channels:
  - conda-forge
dependencies:
  - python=3.11
  - numpy
  - scipy
  - xarray
  - netcdf4
  - h5netcdf
  - scikit-learn
  - matplotlib
  - tqdm
  - ipykernel
  - jupyterlab
  - pip
  - pip:
      - scikit-dimension
      - -e .

